---
# Name for the created server profile template
server_profile_template: SPT1

# Name for the created server profile
server_profile: server1

# Name of the enclosure group
enclosure_group: EG1

# Name of the server hardware type
server_hardware_type: SY 480 Gen10 1

# Name of the server hardware
server_hardware: 0000A66101, bay 11

# Name of the network
network: network1
